### ISSUE TITLE
[lesson0] 시작해볼까요?

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#1]
repo 이름이 좀 많이 아쉽네요.. ^^..

레슨을 시작해볼까요 :)

1. C# Console Application으로 프로젝트를 시작하여. 'hello world'를 출력하는 코드를 구현 후. push해주세요.
2. 'gitignore'이란 게 있습니다. 이를 공부해보시고, 이 프로젝트에 적용해주세요.
    - 완료 후 댓글로 간단한 설명도 달아주시구요.

**Comment by rbsejin** [comment]
컴파일시 program.cs 외의 다른 파일들을 숨겨서 업로드하기 위해 ignore을 사용합니다.

**Comment by huinalam** [comment]
지금 적용한 gitignore로는 다른 사람이 clone할 경우, 실행이 안되겠네요.. 이 부분을 고민해보시구요.

1. .gitignore이 어떤 용도로 사용하는지 간략하게 설명해주시겠어요?
2. .gitignore template를 찾아보시면 관련 정보가 많은데요. 이런게 왜 필요한걸까요? 그리고 지금 적용된 gitignore과 어떤 차이점이 있는지 생각해보세요.

**Comment by rbsejin** [comment]
0.	Gitignore 파일에 program.cs를 제외한 모든 파일을 목록에 추가하여서 program.cs만 commit 되었습니다. 따라서 다른 사용자들은 program.cs만 pull되기 때문에 HelloWorld 를 실행할 수 없었습니다. 제가 여기서 착각했던 것이 ignore을 commit 되는 목록에만 보이지 않고 실제로는 파일이 commit 된다고 착각해서 일어난 일이었습니다.
1.	Gitignore 이란 불필요한 파일을 commit에서 제외하고 싶을 때 사용합니다.  .gitignore 파일에 해당 파일(또는 확장자)을 목록에 추가하여 무시할 수 있습니다.
2.	언어와 에디터에 따라서 ignore해야할 파일을 정리해 놓아서 사용자가 직접 .gitignore파일을 작성할 필요 없이 복사해서 편리하게 ignore 을 할 수 있습니다.

**Comment by huinalam** [comment]
좋은 답변이네요 :)
그런데 commit되어 있는 HelloWorld2는 뭘까요..?
소스코드는 최대한 깔끔하게 정리해두는 편이 좋답니다. 정리 부탁드리구요.

해당 이슈는 close 하겠습니다.
수고하셨습니다 :)
