### ISSUE TITLE
[Lesson 8] 중간에 종료 가능하게 만들기

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#10]
# [Lesson 8] 중간에 종료 가능하게 만들기

숫자 0을 입력하면 프로그램이 어떤 상황에 있든 종료하게 만들어야 한다. 사용자가 종료하기 위해 '0'을 입력하면 아래의 메세지를 표시하도록 하자.
 
```
Thank You 
``` 
 
- 제한사항
  - Thank You 를 표시한 뒤에는 프로그램을 종료 시킨다. 
  - git에서 'develop' branch로 분리하여 개발을 진행한다.

**Comment by rbsejin** [comment]
처음 설계 때부터 중간에 종료가능하게 설계를 하여서 특별히 수정할 것이 없을 것 같습니다.

**Comment by huinalam** [comment]
하하^^.. 미리 레슨 과제가 무엇이 있는지 알게된게 좋은건지 아닌건지 헤깔리네요.
수고하셨습니다.

**Comment by rbsejin** [comment]
아.. 물론 그것도 있지만 처음 설계때부터 중간에 종료 가능하게 설계해서.. 별로 수정할게 없었어요..

**Comment by huinalam** [comment]
@rbsejin 
그렇군요. 미리 고민되어있었다니, 좋은 습관입니다 👍
