### ISSUE TITLE
[Lesson 10] Pattern 추가

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#11]
아래의 Pattern 을 추가한다.
아래의 예는 4 라고 입력된 예이며, 4 번 반복된다. 

```
* 
 
*
** 
 
*
**
*** 
 
*
**
***
****  
```

- 제한사항
  - 테스트코드를 작성한다.

**Comment by huinalam** [comment]
레슨 9는 git merge과정인데, 이미 branch로 써보신 경험이 있으시니 스킵합니다.

**Comment by rbsejin** [comment]
Pattern 추가 완료하였습니다.
기존에 패턴을 추상화하였던 방식이 쓸모없게 되어서 고민을 많이 하다가 그냥 베이직 패턴을 반복하는 방식으로 변경하였습니다.
입력값과 라인수가 같은 유형과 그렇지 않은 유형을 나눠서 추상 클래스를 따로 만들까하는 생각도 해봤는데 참 어렵네요. 일단 동작은 잘하기에 커밋했습니다. 쓴소리(조언)가 절실합니다.

실제로 현업에서  예상하던 방식과 전혀 다른 방식으로 수정해야 하는 일이 비일비재하겠다는 생각도 많이 하게 되었습니다.

**Comment by rbsejin** [comment]
고민하다가 Pattern 추상클래스 하위 클래스로 PatternReapeatedByLine 추상클래스를 생성하였습니다.

**Comment by huinalam** [comment]
많은 고민 좋습니다^^

1. Pattern프로젝트에 소스코드가 참조가 안되는 현상이 있어요. 이 문제를 해결해주시구요.

2. "RepetitionOfBasicsPattern"클래스는 Pattern 클래스로부터 상속 받았음에도 ConfirmCondition는 구현하지 않는다니.. 좀 이상하죠? BuildPattern도 있고 MakePattern도 있고.. 같은 표현인데 또 다르게 동작하네요.
- 부모클래스가 지나친 제약을 가진 탓에 코드가 확장하는 방식이 막힌 이슈에요. 물론 만들어낸 제약이
 지금까지의 요구사항으로 봤을 때는 생산성을 강화할 수도 있지만, 이후에 들어오는 요구사항에 대해서는 지금과 같은 문제를 겪게 만들 수 있지요.
- 자식클래스가 부모클래스에게 지나치게 구현 의존도를 받고 있습니다. Abstract의 장점이자 단점인데요. 저는 Abstract 클래스를 구현하게 되면, 개념적으로 구현 범위를 최소화하는게 좋다고 생각합니다. Pattern은 Pattern까지 그리는 역할로 마무리한다! 인거지요. 그 이상은 이 클래스의 자식들이 할 일이 아니야! 라고 말입니다. 그럼 지금과 같은 요구사항에서는 어떻게해야할까요. 힌트를 드리자면, Line을 반복적으로 해서 그리는 다른 개념(클래스)을 만들면되죠. Pattern은 Pattern을 그리는 것까지 역할을 다한겁니다. 그 이상의 다른 역할은 다른 역할을 해낼 클래스를 만들어서 일을 시키면 되지요.
- Pattern안에 모든 걸 다 넣어야한다는 생각 때문에 "PatternReapeatedByLine"라는 개념적으로 좀 더 복잡해진 클래스가 탄생한 것 같습니다. 나쁘진 않기는 하지만, "NotImplementedException"을 만들어서 구현해야한다면 설계 상의 미스로 보는게 맞습니다.
- 다른 쉬운 힌트를 드리자면 Interface를 쓰는 것도 방법입니다. 동일한 BuildPattern 메서드 역할을 한다는 제약만 걸어두고 구현은 알아서 하시오-라고 제약을 주는거죠.
- 한번 설계를 다시 잡아보세요. 많이 느끼시겠지만, 유지보수와 재사용이 쉬운 디자인이란게 참 쉬운게 아니랍니다.

**Comment by huinalam** [comment]
더 생각할 것을 드리자면...
`전략패턴`을 찾아보시고 이해해보시면 많이 도움되실 것 같습니다.

**Comment by rbsejin** [comment]
Pattern 클래스에 BuildPattern 추상 메소드만 상속받게 하였습니다.
결국 많은 시간동안 한 게 이게 다네요.

인터페이스를 안쓰고 추상 클래스를 쓴 이유는 패턴문자를 필드에서 사용하기 위해서입니다.

전략패턴에 대해서도 알아보았는데요. 이 프로젝트에서는 각 패턴의 메소드의 내용이 변경되거나 중복될 것 같지 않아서 사용하지 않았습니다. 예를 들어 Reverse패턴 한가지가 아니라 여러개 있어서 수시로 변경된다면 사용할 것 같은데, 이번 프로젝트는 각 패턴이 모두 다르게 하나씩 고정되어있어서 굳이 사용해야할지 잘 모르겠습니다. 어떻게 사용할지 감이 잘 안 잡힙니다. 만약 각 패턴의 입력값 제한이 자주 바뀐다거나 하면 전략패턴을 활용하면 좋을 것 같습니다.

**Comment by huinalam** [comment]
'입력값 제한이 자주 바뀐다면 전략패턴이 적절하다'는 걸 잘 이해하셨군요. 다시 고민해보니 현재 구현된 코드에서 전략패턴으로 가면 수정범위가 크긴 하네요. 체크 기능을 빼면서 Pattern으로 간거군요.

다만 몇가지 더 언급하고 싶기는 한데.. 아쉽지만 시간이 하루 이틀밖에 안남았으니, 마지막에 기회가 되면 더 이야기하도록 하죠.

수고하셨습니다.
