### ISSUE TITLE
[Lesson 11] Pattern 추가 

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#12]
# [Lesson 11] Pattern 추가 

아래의 Pattern 을 추가한다.

```
*     *      *       
      **     **
             *** 
```

- 제한사항
  - 각 Pattern 간의 간격은 일정하도록 한다.  입력된 줄 + 2 줄 
  - 테스트코드를 작성한다.

**Comment by rbsejin** [comment]
새로운 패턴 추가하였습니다.
그런데 테스트코드 검사가 안되네요?
이유를 모르겠습니다.

**Comment by huinalam** [comment]
어떻게 안된다는건지요? 스크린샷이나 에러코드를 올려주시겠어요?

**Comment by huinalam** [comment]
저는 테스트 코드가 잘 동작하네요.
다만 'BuildHorizontallyRepetitionOfBasicsPattern' 테스트가 실패로 나오네요.
덧붙여, 'HelloWorld.sln.bak'은 솔루션 백업파일이에요. 굳이 commit하지 않으셔도 됩니다.

**Comment by rbsejin** [comment]
![default](https://user-images.githubusercontent.com/33508993/36741648-fc9e3c90-1c28-11e8-8559-4f6c6c69439a.png)

**Comment by huinalam** [comment]
저기 말대로 솔루션 빌드 한번 해보시겠어요?
vs 재시작도 해보시구요.

**Comment by rbsejin** [comment]
다 해봤는데 안되네요. 제 비쥬얼 스튜디오 문제인가봐요.

**Comment by huinalam** [comment]
테스트가 안되면 진행이 어려울텐데요..
빌드에서 솔루션 Clean해보세요. 그 다음 재빌드를 해보세요.

제가 다른 PC에서 소스코드를 Clone해서 받아봤는데, 테스트가 잘 동작했습니다.

**Comment by huinalam** [comment]
![image](https://user-images.githubusercontent.com/4952867/36765187-5bccbdbe-1c73-11e8-8b20-6fa6c27ea93e.png)

**Comment by rbsejin** [comment]
![image](https://user-images.githubusercontent.com/33508993/36766101-baac5070-1c77-11e8-84a4-d5a9af270b93.png)

왜그런지는 모르겠지만
MSTest.TestFramework 버전을 1.2 에서 1.1.18로 바꾸니 되네요.

**Comment by huinalam** [comment]
저는 1.2에서 잘 됐는데, 1.2 패키지가 잘못된건가 싶기도 하네요.
일단 이걸 또 붙잡고 원인을 찾다보면 시간이 많이 걸리니, 나중에 다시 보도록하죠!

수고하셨습니다.
