### ISSUE TITLE
[Lesson1] 첫 Pattern

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#2]
아래와 같이 표시되도록 코드를 작성해보세요.
 
```
* 
**
***
****
***** 
```

**Comment by rbsejin** [comment]
이제서야 확인을 해서 코드 작성하고 바로 올립니다.

**Comment by huinalam** [comment]
아차. 제가 제한조건을 달지 않았네요.
hello world를 구현한 프로젝트 코드를 수정해서 만들어주세요.

**Comment by rbsejin** [comment]
HelloWorld 프로젝트를 수정해서 다시 완료했습니다.

**Comment by huinalam** [comment]
@rbsejin 
네 잘하셨어요. 구현 방식이 재미있네요. 차후 어떻게 바꿔어갈지 기대되네요 ^^
해당 이슈는 클로즈하겠습니다. 수고하셨습니다.
