### ISSUE TITLE
[Lesson 2] 사용자가 입력가능하도록 만든다.

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#3]
Lesson 1의 프로젝트를 수정하여 사용자가 몇 줄을 찍을 것인지 할 수 있도록 한다.

``` 
How many lines? (1..100)  7
*
**
***
****
*****
******
******* 
```

- 제한조건
  - 사용자는 1 부터 100 까지의 값을 칠 수 있다. 
  - 사용자가 0 이나 마이너스 값을 치는 경우에는 아래와 같이 표시하고 input 을 다시 요구한다. 100 보다 큰 경우에도 마찬가지이다.
  - 사용자가 정상 값을 칠 때까지 계속 입력을 받는다.
  - 정상적으로 입력하면, 화면에 표시하고 종료한다. 
 
```
Invalid input – Range 1..100
How many lines? (1..100) 
```

**Comment by rbsejin** [comment]
완료했습니다!

**Comment by huinalam** [comment]
@rbsejin 

1. [코드리뷰](https://github.com/rbsejin/project1/commit/bdbbc33acc58ed22c14a41ec14446ba0c194476b)를 참고해주세요.

2. 문자값을 입력시 에러가 나네요. 문자값이 들어갈 경우, 입력을 취소해주세요.

**Comment by rbsejin** [comment]
바로하려고 했는데 다른 일을 하느라(핑계) 이제야하는군요.
아무래도 return 메소드를 따로 만드는 것보다는 call by reference 로 하는 것이 나을 것 같아서 고쳤구요.
그리고 입력값이 문자일 경우의 예외처리를 하였습니다.  그런데 이 때의 예외처리 클래스가 FormatException 인지는 잘 모르겠네요.
감사합니다.

**Comment by huinalam** [comment]
아직 push를 하지 않은 것 같네요.

**Comment by rbsejin** [comment]
push 했는데 이상하네요... 다시 한번 push 했습니다.

**Comment by huinalam** [comment]
ㅎㅎ 아마 시험기간이 조금 바쁘셨겠죠. 이제 속도를 내보도록하죠.

각 커밋마다 코드 리뷰를 해두었습니다.

그리고.. 'out 키워드를 이용하여 Input 메소드에서 매개변수를 call for reference 로 넘겨 입력값을 받아옴' 커밋은 커밋된 코드와 커밋 메세지 내용이 다르네요 ^^... 주의 부탁드릴께요.

**Comment by rbsejin** [comment]
말씀하신것 모두 수정하였습니다! 정말 감사합니다.

**Comment by huinalam** [comment]
간단한 코드리뷰를 남겨두었습니다. 보시고 수정 부탁드리구요.

잘 마무리 하셨습니다. 바로 다음 레슨으로 넘어가보죠 ^^
