### ISSUE TITLE
# [Lesson 3] 새로운 Pattern

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#4]
# [Lesson 3] 새로운 Pattern

아래의 2 가지 Pattern 을 추가하고 (총 3 개의 Pattern 이 된다)
사용자가 원하는 Pattern 을 선택할 수 있도록 한다. 

```
- Pattern 추가
*****
 ****
  ***
   **
    * 
 
- Pattern 추가
   *
  ***
 *****
  ***
   * 
```

- 제한사항
  - 잘못된 Input 이 들어오면 다시 입력을 받도록 한다.
  - Input 입력방법은 정해져 있지 않다.
  - 사용자가 이해하기 쉬운 것을 제안하라.
  - 다이아몬드 형태의 입력은 홀수만 입력되도록 한다.
  - 정상적으로 선택한 후 종료한다.

**Comment by rbsejin** [comment]
사용자가 이해하기 쉬운 것을 제안하라 라는 말이 정확히 어떤 의미인지 궁금하네요.
일단은 완료했습니다.

**Comment by huinalam** [comment]
코드가 흥미롭게 구현되어 있네요 ^^..
앞으로 어떻게 변화해갈지 궁금하네요.

https://github.com/rbsejin/project1/commit/64e14fe88a2b46c71819f99aac107985955fe842
위 코드리뷰를 보시고 코드를 수정해주세요.

**Comment by rbsejin** [comment]
메소드의 이름 첫글자를 모두 소문자에서 대문자로 바꿨습니다.
일단 네이밍 규칙을 다 살펴봤는데 또 다른 문제가 있는지는 모르겠네요.
혹시 또 다른 문제가 있다면 알려주세요.

**Comment by huinalam** [comment]
https://github.com/rbsejin/project1/commit/cdcc712e39845fb05d786291cdc84440dbcee815

리뷰를 달아두었습니다.

항상 코드 컨벤션이 일관성있어야 보기에 좋습니다.
한번 더 살펴보시고, 수정을 해주세요.

**Comment by rbsejin** [comment]
리뷰 달아둔 것 수정하였습니다. 코드 컨벤션에 더 유의하도록 하겠습니다.

**Comment by huinalam** [comment]
많이 깐깐했죠?
코드를 구현하여 동작하는 것도 중요하지만, 코드 스타일을 일관성 있게 유지하는 것도 중요하답니다.
특히 혼자 구현하는 게 아니라 다른 사람과 같이 협업할 땐 더욱 더 중요하구요.
여러 명이서 같은 소스코드를 수정한다면, 서로 같은 스타일을 유지할 수 있을 때, 가독성이 좋아지거든요.
가독성이 좋은 만큼, 코드도 잘 읽혀지고, 소통하기도 좋지요.

수고하셨습니다 ^^
