### ISSUE TITLE
[Lesson 4] 무한 Loop 및 Pattern 추가

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#5]
한번 하고 종료되지 않고, 계속 Loop 를 돌도록 만든다.
아울러, 아래의 Pattern 을 추가한다. 
 
```
- Pattern 추가
   ***
  ***
 *** 
 
- Pattern 추가
   ***
  **
 * 
```

**Comment by rbsejin** [comment]
완료하였습니다. 이번에는 빈틈이 없을 것이라 예상해봅니다.

**Comment by huinalam** [comment]
하핳
자신감 넘치시는 걸 보니 좋네요^^..

1. 
visual studio에서는 auto format이라 하여 document format을 맞쳐주는 기능이 있답니다.
ctrl+k+d를 눌러보세요.(아마 기본설정으로 설치하셨다면, auto format 단축키일겁니다.) 그리고 git diff로 어떤 차이를 확인 후 고쳐주세요.
- visual studio에서 포멧은 변경할 수 있습니다. 일단 우리는 기본 포멧 설정에 따르도록 하지요.

2.
C#에는 XML문서 주석을 달 수 있습니다.
InputValue 클래스의 메서드에 주석이 달려있는데, 이를 XML 주석을 활용해 수정해보세요.

3.
네이밍을 고민해볼까요.
InputValue 클래스에 InputNumber, InputString 메서드... input이 class 명과 method 명에 동시에 쓰이니, 의미가 불명확하게 보이네요.
입력값.입력숫자?
입력값.입력문자?
좀 더 적절한 네이밍이 없을까요?

3.1
InputValue의 InputNumber, InputString에 보면 둘다 out 키워드를 활용해 값을 리턴하는데요. 그냥 리턴해도 될텐데, out 키워드를 활용한 이유가 있는지요?

**Comment by rbsejin** [comment]
1. auto format 유용하게 쓰겠습니다.
2. XML 태그유형에 대해서 더 공부해야겠지만 기본적인 사용법은 익혀두었습니다.
3. 네이밍은 정말 고민이 되네요. 바꾸긴 바꿨는데 잘 한건지....
그리고 Input 메소드를 문자형, 정수형 두가지로 두지 않고 하나로 오버로딩하였습니다.
4. 처음 코딩할 때 생성자로 코딩을 해서 리턴을 사용하지 않고 참조에 의해서 전달했었는데
메소드로 변경한 후 수정을 하지 않았었네요. 수정하였습니다.

네이밍은 정말 어렵네요.

**Comment by rbsejin** [comment]
실험1을 branch 해서 만들었습니다.
내용은 반복문에서 break문 없애기와 부울변수 사용하기입니다.
먼저 break문은 왠만하면 사용하지 않는 것이 좋다고 하여서
end일 때 반복문을 빠져나가는 것 하나만 두고 전부 수정하였습니다.
다음으로는 식을 그대로 사용하기보다 변수로 사용하는 것이 가독성 측면에서 좋다고 하여서
수정해봤는데 잘 한 것인지는 모르겠네요.

**Comment by huinalam** [comment]
1. Reader.Input ... 읽기.쓰기... 좀 이상하죠.. ^^.. 정답이 존재하는게 아닌지라 늘 고민하게 만들죠. 네이밍은 레슨 진행하는 동안 숙제로 가져가기로 하죠.
 다른 사람들의 C# 코드를 찾아 읽어보다보면 도움 많이 되실거에요.

2. 벌써 branch까지 쓰시다니.. 실은 레슨 후반에 있는데 미리 git 공부하시고 응용하시는걸 보니 좋네요ㅎ
 다만 지금은 레슨중이니 master로 통합하면 어떨까요?

3. while 문에서 break문을 사용하지 않는게 왜 안좋은걸까요?

4. 주석을 달면서 라인 정리가 안되어 있네요. 다시 정리를 부탁드릴께요.

**Comment by rbsejin** [comment]
1. 고민해보겠습니다.
2. 기존 master을 지우고 실험1을 master로 변경하였습니다.
3. 순차적이지 않고 급격히 제어를 건너뛰는 코드는 좋지 않다고 들었습니다.
코드를 어렵게 만들기 때문이죠.
그래서 가능한한 반복문에서 break는 사용하지 않으려고 합니다.
4. 라인정리가 어디가 안되있는건지 모르겠네요. 방금 다 확인했는데...

**Comment by huinalam** [comment]
3. 그렇네요. 그점은 저도 유의하지 않고 쓰고 있었네요. 덕분에 배워가네요ㅎㅎ

4. 

- 여기 보면 중괄호랑 붙어있어요.
https://github.com/rbsejin/project1/blob/master/HelloWorld/HelloWorld/Program.cs#L6

- 아래는 메서드 간에 1줄씩 띄우면 좋겠네요.
https://github.com/rbsejin/project1/blob/master/HelloWorld/HelloWorld/Program.cs#L69

**Comment by rbsejin** [comment]
4. 아하 알겠습니다. (매의 눈ㅋㅋㅋ)

**Comment by huinalam** [comment]
그리고 주석은 코드 뒤에 넣기보다 별도의 줄에 넣는걸 권장합니다.
아래 링크를 한번 참고해보시고 정리해볼까요 ^^..

[C# 코딩 규칙](https://docs.microsoft.com/ko-kr/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)

**Comment by rbsejin** [comment]
주석 모두 수정하였습니다. 그런데 문장이 아닌 경우에도 마침표(.)를 찍는지 궁금합니다.

**Comment by huinalam** [comment]
줄을 띄운다는게, 각 메서드간에 빈 line을 1줄씩 넣자는 말이었어요 ㅎㅎ

마침표까지 딱 맞추는 규칙을 본 적은 없었던 것 같네요. 개인적인 견해로는 굳이 주석의 마침표까지 맞출 필요가 있을까 싶네요.

**Comment by huinalam** [comment]
예를 들자면..
```
        }
        /// <summary>
        /// 기본형 별패턴 출력 메소드
        /// </summary>
        /// <param name="number">행의 수</param>
        public void PrintBasicStarPattern(int number)
        {
```
위의 코드를 아래처럼..

```
        }

        /// <summary>
        /// 기본형 별패턴 출력 메소드
        /// </summary>
        /// <param name="number">행의 수</param>
        public void PrintBasicStarPattern(int number)
        {
```

**Comment by rbsejin** [comment]
네 메소드 간의 한줄 띄는 것은 모두 완료했습니다.

**Comment by huinalam** [comment]
아직 푸시된 커밋이 없는데 확인해주시겠어요?

**Comment by rbsejin** [comment]
제가 comment에 내용을 잘못 적어서 입력하는 바람에요 ㅠㅠ 1. exit를 판단하는 ~ 에 수정하였습니다.

**Comment by huinalam** [comment]
https://github.com/rbsejin/project1/issues/5#issuecomment-354601193

위 이슈에 대해선 아직 수정 안된 것 같은데.. 확인 부탁드릴께요.

**Comment by huinalam** [comment]
아차.. 수정되었군요.

https://github.com/rbsejin/project1/blob/master/HelloWorld/HelloWorld/Program.cs#L6

이것도 확인을 해주세요 ^^

**Comment by huinalam** [comment]
덧붙여서 xml주석으로 return 값에 대해서도 주석을 달 수 있어요.

https://github.com/rbsejin/project1/blob/master/HelloWorld/HelloWorld/Program.cs#L240
https://github.com/rbsejin/project1/blob/master/HelloWorld/HelloWorld/Program.cs#L275

위 코드에 <returns>로 시작하면 주석을 달아주세요.

**Comment by rbsejin** [comment]
아 네임스페이스에 한 칸을 안띄웠군요.
return 값에 대해서도 주석을 달았습니다.

**Comment by huinalam** [comment]
https://github.com/rbsejin/project1/blob/master/HelloWorld/HelloWorld/Program.cs#L6

여기 잘못 수정한 것 같은데요..

**Comment by rbsejin** [comment]
네 수정했습니다.

**Comment by huinalam** [comment]
수고하셨습니다.
좀 지루할 수 있었겠지만, 처음보다 코드가 휠씬 깔끔해지고 좋네요.

다음 레슨으로 넘어가보도록 하죠^^
