### ISSUE TITLE
[Lesson 5] Source File 리팩토링

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#6]
# [Lesson 5] Source File 리팩토링

이전처럼 앞으로도 요구사항에 따라 코드가 계속 수정될 예정이다.
어떻게 프로젝트 구조를 설계하면, 기존 코드를 많이 변경하지 않으면서도 새로운 기능을 큰 변경없이 쉽게 넣을 수 있을지, 고민해보고 변경해보라.

- 힌트
  - interface나 abstract를 활용한다.
- 도전과제
  - 디자인 패턴을 찾아 응용해보아도 좋다.

**Comment by rbsejin** [comment]
일단 StarPattern 을 추상클래스로 하고 상속받아 클래스를 선언을 했습니다.
그래도 새로운 Type의 StarPattern 을 추가할 때 여전히 Main 메소드에서 많은 코드의 수정이 불가피하네요.

**Comment by huinalam** [comment]
잘하셨습니다. 추상클래스를 잘 활용하셨네요. 코드가 진화해가는 걸 보니 흥미롭네요.
이왕이면 한 클래스 파일 안에는 하나의 클래스만 있는게 좋습니다.  코드가 난잡해지는 걸 막기 위해서죠.
클래스도 여럿 생기게 될테니 네임스페이스도 지정해보면 어떨까요?

**Comment by huinalam** [comment]
그리고 하나 더 ^^..
추상 클래스를 잘 활용하시긴 하셨는데, 활용 방식은 기존의 방법과 똑같네요. 추상클래스의 활용 용도를 좀 더 고민해주시겠어요? 코드를 작성함에 있어, 좀 더 중복적인 작업을 피할 수 있는 방법이 있을 것 같네요.

**Comment by rbsejin** [comment]
제 나름대로 중복적인 작업을 피할 방법을 생각해봤는데 아무래도 이상한 같네요.

**Comment by huinalam** [comment]
ㅎㅎ 소스코드를 읽고 있는데, 고민한 흔적들이 많이 남아있네요. 이렇게 저렇게 고친 시도들이 많이 보입니다.
정해진 답은 없어요. 더 나은 방법이 무엇인지 계속 고민하며 찾아가고 있다면, 고민이 차츰 여물어가며, 더 나은 코드를 구현하실 수 있을거에요.
리프레쉬 차원에서 레슨 5.5를 중간에 하도록 하겠습니다. 자세한건 5.5 레슨을 봐주세요^^

**Comment by huinalam** [comment]
이번 이슈는 세진님이 직접 클로즈할지 계속할지 결정하면 좋겠네요. 어떻게 할까요?

**Comment by rbsejin** [comment]
아무래도 코드가 너무 엉망이 된 것 같아서 다시 뜯어고치고 있어요.
윤배님 코드보고 좀 고칠 부분이 많이 생각나서 어느 정도 정리한다음에 다시 올리겠습니다.
그리고 클로즈하도록 하면 어떨까요?



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

2018-01-16 13:19 GMT+09:00 huinalam <notifications@github.com>:

**Comment by huinalam** [comment]
하하.. 저는 동작하는 코드는 엉망이 아니라 생각해요.

유명 스타트업 일화인데요. 안드로이드 앱으로 대박을 치며 많은 사람들이 사용했는데, 실은 그 안드로이드 앱 패키지 이름이 초기에 설정되는 'Application1'인가 그랬다고 하더군요. 처음 개발하셨던 분이 프로젝트 이름을 어떻게 설정해야할지 몰라서 기본 이름으로 시작한거죠. 좀 시간이 많이 걸려서야 이름이 나름 개발스럽게(?) 바뀌었다고 하더군요.

우리가 하는 레슨은 '동작하는 코드'보다 '동작하는 코드, 그 이후'를 더 중점으로 두고 있어요. '만들어진 코드를 어떻게 관리해나갈 것인가?' 이 점을 염두하고 계속 진행하고 있답니다.

코드는 잘 동작하고 있으니, `리팩토링`을 해보세요. 이번주 토요일날 같이 만나서 같이 이야기를 나눌 예정이니, 윤배님이 세진님 코드를 리뷰할 수 있도록 그 전에 여유있게(?) 완료해주시면 좋겠어요 ^^
