### ISSUE TITLE
[Lesson 5.5] 서로의 코드를 리뷰해주기

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#7]
# [Lesson 5.5] 서로의 코드를 리뷰해주기

같이 레슨 중인 분과 코드를 한번 리뷰해봅시다.
1. 다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
2. 다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.

**Comment by huinalam** [comment]
https://github.com/bykauienm/git_test

위 소스는 같이 레슨중인 윤배님 코드입니다.

**Comment by rbsejin** [comment]
1. 다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
 1.1. 패턴을 문자열에 저장하여 한 번에 출력하는 것이 제가 생각하지 못한 부분이었습니다.
 1.2. 행렬을 먼저 만들고, 행마다 *을 찍을지 공백을 찍을지를 선택하도록 한 부분이 인상적이었습니다.
 1.3. StringBuilder 를 이용하여 실행 속도를 빠르게 한 것이 좋았습니다.
 1.4. 출력,입력화면이 굉장히 깔끔해서 보기 좋았습니다.

2. 다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.
 2.1. 행렬을 만들고 *을 찍을지 말지를 선택하도록 패턴을 만든다면 새로운 패턴이 추가될 때 행,열과 *를 찍는 선택조건만 변경하면 쉽게 패턴을 추가할 수 있다고 생각됩니다.
 2.2. 콘솔화면에서 출력된 문자를 없애는 법을 몰라서 계속 아래로 내려가는 방식으로 구현했는데 이를 갈끔하게 수정해야겠다는 생각을 합니다.

**Comment by huinalam** [comment]
@rbsejin 
레슨하시는 다른 분 코드에 대한 리뷰는 그 분의 이슈에 적어주시면 어떨까요?
아래 링크 타시면 됩니다.

https://github.com/bykauienm/git_test/issues/11

**Comment by bykauienm** [comment]
1. 다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
- summary를 달아 메서드에 대해 쉽게 알 수 있는게 좋았습니다.
- 범위 체크나 * 이나 공백을 리터럴 그대로 사용하지 않고 상수로 사용하는게 좋았습니다.

- 클래스와 클래스 파일의 이름을 같게 하거나, 클래스 Pattern을 상속을 받는
 비슷한 클래스들을 따로 폴더를 만들어 분류하면 좀더 보기 편하지 않을까 합니다.

2. 다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.
- 지금은 코드가 짧아 괜찮지만 summary나 주석이 없었습니다. 향후를 위해
앞으로는 잘 쓰도록 해야겠습니다.
- 범위나 출력 문자열을 리터럴 그대로 쓴게 많은데 상수를 이용해 작성할 수
있도록 더 신경써야겠습니다.
- FindPattern 메서드 등의 매개변수로 "1", "2" 와 같은것들에 좀더 의미부여 할 수
있는 방향으로 생각을 해봐야겠습니다.

**Comment by bykauienm** [comment]
1. 다른 분의 코드에서 '좋은 점'과 '느낀 점'을 적어주세요.
- summary를 달아 메서드에 대해 쉽게 알 수 있는게 좋았습니다.
- 범위 체크나 * 이나 공백을 리터럴 그대로 사용하지 않고 상수로 사용하는게 좋았습니다.

- 클래스와 클래스 파일의 이름을 같게 하거나, 클래스 Pattern을 상속을 받는
 비슷한 클래스들을 따로 폴더를 만들어 분류하면 좀더 보기 편하지 않을까 합니다.

2. 다른 분의 코드를 본 후, 자신의 코드에 대해 리뷰를 해보세요.
- 지금은 코드가 짧아 괜찮지만 summary나 주석이 없었습니다. 향후를 위해
앞으로는 잘 쓰도록 해야겠습니다.
- 범위나 출력 문자열을 리터럴 그대로 쓴게 많은데 상수를 이용해 작성할 수
있도록 더 신경써야겠습니다.
- FindPattern 메서드 등의 매개변수로 "1", "2" 와 같은것들에 좀더 의미부여 할 수
있는 방향으로 생각을 해봐야겠습니다.

**Comment by rbsejin** [comment]
오늘 날잡고 코드를 싹다바꿨네요.
제대로 생각해서 구현안하고, 컴퓨터 앞에서 구걸해가며 코딩해서 코드가 알아보지 못할 정도로 엉망이 되어버렸습니다.
일단 더 고쳐야할 부분은 Diamond 패턴처럼 짝수만 입력받을 경우 일일이 선택문을 넣어서 고쳐야하는데 이 부분은 윤배님이 작성한 코드처럼 Dictionary 컬렉션과 패턴유형 각각에 범위 처리 메소드를 두면 편리할 것 같습니다.

**Comment by bykauienm** [comment]
클래스들을 분류하고난 뒤 보기가 더 편해져서 좋습니다.
패턴의 출력부분에서 "*"과" "의 조건검사 부분만 추상화 한게 인상적이네요. 좋아 보입니다.

A = B == C 와 같은 부분들을 보기좋게  A = (B == C) 처럼 괄호로 감싸는건 어떨까요

**Comment by huinalam** [comment]
@rbsejin @bykauienm 

https://github.com/rbsejin/project1/commit/a9e0e4f9de8198afea878821d0659ea5662962b1#diff-5a0cdb3aa00a6a5ce827fbe93ca72a8aR35 이 부분 언급하신 것 같네요.

**Comment by huinalam** [comment]
@rbsejin 위 윤배님 코맨트에 답변 해주시면 좋겠어요

**Comment by rbsejin** [comment]
아 정말 죄송합니다. 윤배님이 코멘트 달아주신 것을 몰랐네요.ㅠㅠ
윤배님 너무 감사합니다. 패턴 출력 부분에 대해서 고민을 많이 했는데 칭찬받아 뿌듯하네요.
대입연산과 비교연산이 있는 식의 경우 윤배님처럼 하면 좋겠다는 생각을 안그래도 하던 참이었는데 역시 필요한 부분을 잘 지적해주신 것 같습니다. 조언 감사합니다.

**Comment by huinalam** [comment]
더 이상 코맨트가 없을 것 같아, 이 이슈는 종료합니다.
