### ISSUE TITLE
[Lesson 6] Library로 만들기

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#8]
# [Lesson 6] Library로 만들기

메인부분을 제외한 입력부분과 수행부분을 라이브러리로 만들고, 메인 프로젝트가 라이브러리를 reference로 참조하여 사용하게 만든다. 라이브러리 이름은 스스로 정한다.

**Comment by rbsejin** [comment]
죄송합니다. 거의 보름이나 걸렸네요. 라이브러리 추가하였습니다.

**Comment by huinalam** [comment]
기존의 코드를 다시 새롭게 구현하는건 어려운 일이에요. 엄청 고생하셨어요.
라이브러리로 잘 나누셨습니다.

코드 하나하나 일일이 코맨트 달아두신게 인상적이네요.

언제나 그렇듯.. 작은 이슈들을 해결해보죠..^^

https://github.com/rbsejin/project1/blob/cddb5f17b1266793cfce2ee6a5f0e31b22e6b415/HelloWorld/Read/ReaderPrinter.cs#L14
- 의미가 없는 주석은 삭제하면 어떨까요?

https://github.com/rbsejin/project1/blob/cddb5f17b1266793cfce2ee6a5f0e31b22e6b415/HelloWorld/Read/ReaderPrinter.cs#L109
- if-else문 주석 위치를 일관성있게 배치해주세요. 어떤 주석은 if문 위에, 어떤 주석은 if문 아래에 있네요.

https://github.com/rbsejin/project1/blob/cddb5f17b1266793cfce2ee6a5f0e31b22e6b415/HelloWorld/Pattern/Pattern.cs#L10
- 추상 클래스인 Pattern 클래스를 Patterns 네임스페이스가 같이 넣어두면 좋을 것 같아요. 상속 받은 클래스드들이 그곳에 다 같이 있으니까요.

[Patterns](https://github.com/rbsejin/project1/tree/cddb5f17b1266793cfce2ee6a5f0e31b22e6b415/HelloWorld/Pattern/Patterns)
- Pattern클래스를 상속받은 클래스인 만큼, 이름에 Pattern이 들어가면 좋을 것 같습니다. 가령 BasicPattern처럼요.

**Comment by rbsejin** [comment]
말씀하신 내용 모두 수정하엿습니다!

**Comment by huinalam** [comment]
코드가 나날이 발전하는 걸 보니 즐겁네요ㅎㅎ
이슈를 닫습니다.
