### ISSUE TITLE
[Lesson 7] Test Code 구현하기

### ISSUE THREAD

**Issue by huinalam** [rbsejin/project1#9]
# [Lesson 7] Test Code 구현하기

기존 프로그램의 '입력부분', '수행부분'에 대한 테스트 코드를 구현한다.

- 제한사항
  - MSTest 기반으로 작성한다. (기호에 따라 XUnit등을 활용해도 좋다)
  - 테스트코드는 AAA패턴으로 구현한다.
  - 이후 모든 코드는 테스트 코드를 작성할 수 있도록 구현한다.

- 힌트
  - 테스트 코드는 정상적인 동작 방식을 보장, 프로그램의 점진적 설계, 다른 사람이 코드를 사용하고자 할 때 구현의 의도를 알리려는 목적으로 작성이 된다.

- 힌트 코드
```
[TestMethod]
public void CreateStar() 
{
  // Arrange
  var validResult = "* ** ***";
  var parttern = new StarParttern();
  
  // Act
  var result = parttern.Build(5);

  // Assert
  Assert.Equal(validResult, result)
}
```

**Comment by huinalam** [comment]
아차.. 그리고 이전 커밋에 대한 코맨트입니다.
커밋 메세지는 최대한 한줄로 쓰거나, 아니면 여러 커밋으로 나누거나, 커밋 메세지 요약을 제목으로 적는게 좋습니다. 1,2,3 이렇게 나눠서 적으면 좋긴하지만,  git commit history를 보면 첫줄만 보여서, 나머지 변경건(2,3번)이 보이지 않거든요.

**Comment by rbsejin** [comment]
네 알겠습니다. 다음 커밋에는 참고하도록 하겠습니다

**Comment by rbsejin** [comment]
드디어 테스트 코드를 입력 부분과 출력(동작)부분을 나누어서 작성하였습니다.
테스트 코드를 작성하다보니 입력과 놀리 부분을 나누어서 작성해야하는 이유도 더 분명히 알게 되었습니다.

**Comment by huinalam** [comment]
고민 많았던 만큼 코드가 많이 깔끔해지고 좋네요 ^^
몇가지 지점들을 조언할께요.

1. 사용하지 않는 프로젝트 파일 및 코드들 삭제해주세요. git은 실제 소스코드 변경이력을 저장하고 관리하는 공간이에요. 커밋할 때, 무조건 모든 파일을 commit하기보다 필요한 코드들만 나눠서 커밋하는게 좋아요. git을 사용하는 단순히 소스 이력관리도 있지만, 다른 누군가와 협업하면서 '내가 이런 이유로 이 소스코드를 고쳤다'라는 사실을 알려주는 목적도 있어요. 일단 현재 커밋된 파일 중에 사용하지 않는 소스코드들을 정리하도록 하죠.

2. Project.UnitTests 이름을 가진 프로젝트가 ReaderTests.UnitTests 폴더 아래에 있네요. 이름을 동일하게
 지정해주세요.

3. ReaderPrinter.cs 소스코드를 보면, end, min, max에 컨벤션이 지켜지지 않았습니다.
  - 위와 마찬가지로 커밋 전에 세세하게 체크해주세요. 세진님의 코드 작업을 보면 아쉽게도 디테일한 부분에서 많이 약한게 많이 느껴져요.
  - ReadPatternType() 메서드를 통해 타입을 만들때, int를 사용하여 변환하기 보다 enum을 사용하는건 어떨까요.

4. ReaderPrinterTests.cs 코드가 첨부되지 않은 것으로 나옵니다. csproj를 뜯어보니 잘못된 소스경로를 지정하고 있네요. 한번 확인 부탁드리구요.

5. "Microsoft.VisualStudio.TestPlatform.TestFramework" reference를 참조함에 있어서 상대경로로 지정되어 있네요. 이렇게 될 경우, 다른 개발자가 소스코드를 포크했을 때, 프로젝트를 열 수 없게 됩니다. C#에는 nuget이라는 package 설치 툴이 있습니다. 이를 활용해서 reference를 적용해주세요. nuget에 "Microsoft.VisualStudio.TestPlatform.TestFramework"라고 치면 바로 나옵니다.

**Comment by rbsejin** [comment]
1. 그 동안 무심코 commit 을 넷상에 세이브? 한다는 생각으로 사용했던 것 같네요. 주의하겠습니다.
2. 제가 말씀하신대로 enum 을 사용했는지 잘 모르겠네요.
3. 제가 push를 branch한 develop에 push를 했네요 ㅠㅠ 죄송합니다. 일단 merge 했습니다.

**Comment by huinalam** [comment]
잘 정리가 하셨네요 ^^
다시 꼼꼼히 보니 약간의 문제점이 있네요..

1.  ProjectTests.UnitTest에서 테스트가 실패로 나오네요. 한번 점검해보시겠어요?
2. Reader프로젝트의 ReaderPrinter.cs를 보면 네임스페이스가 HelloWorld로 되어있네요. 네임스페이스는 자신의 dll 이름을 따서 적는게 좋아요. 그렇지 않으면 해당 소스코드가 어디있는지 추측하기 쉽지 않거든요. 의도적으로 같게 지정하는 경우도 있긴 하지만, 우리는 의도가 있는건 아니고 소스코드 옮기는 과정에서 있었던 실수이니, 수정하도록 하죠.
3. 
https://github.com/rbsejin/project1/blob/f4b9aceaf9a14fb8cbddc2bebfec32cec05fa424/HelloWorld/Reader/ReaderPrinter.cs#L119 
컨벤션 이슈에요 ^^...

**Comment by rbsejin** [comment]
1. 제가 실패한 케이스는 테스트도 실패하도록 하는줄 잘못 알았네요. 수정하였습니다.
2. Reader프로젝트 자체가 네이밍이 이상해서 바꾸려고하다가 네임스페이스를 HelloWorld인 것을 그대로 두고 까먹었네요. 수정하였습니다.
3. 컨벤션 ㅠㅠ.

**Comment by huinalam** [comment]
드디어 마무리되었네요^^ 수고하셨습니다.
해당 이슈는 종료합니다.
